app:
  env: 'local'
  port: 8089
  app_name: 'gin-app'
  app_url: 'http://localhost'

log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: app.log # 日志文件名称
  format: # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

mysql:
  driver: 'mysql'
  host: '47.94.169.240'
  port: 3306
  database: 'test'
  username: 'root'
  password: 'mysql@yang1234'
  charset: 'utf8mb4'
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'

jwt:
  secret: '3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s'
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 43200
  refresh_grace_period: 43200

redis:
  host: '47.94.169.240'
  port: 6379
  db: 0
  password: 'redis@yang'

storage:
  default: 'local'
  disks:
    local:
      root_dir: './storage/app'
      app_url: 'http://localhost:8888/storage'
    ali_oss:
      access_key_id: 'access_key_id'
      access_key_secret: 'access_key_secret'
      bucket: 'bucket'
      endpoint: 'endpoint'
      is_ssl: true
      is_private: false
    kodo:
      access_key: 'ZZ1Dkk5K2mbC24sA0W8pdasQA-mCUVTJMLKb8lQ_'
      bucket: 'qiniuyang123'
      domain: 'rilcsdquh.hb-bkt.clouddn.com'
      secret_key: 'ZZ1Dkk5K2mbC24sA0W8pdasQA-mCUVTJMLKb8lQ_'
      is_ssl: true
      is_private: false
